### ISSUE TITLE
NATS: Support File-Based Authentication Options

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/go-mod-messaging#167]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]
NATS message bus client should support file-based authentication options including:

Nkey Seed: https://docs.nats.io/using-nats/developer/connecting/nkey

Credentials File: https://docs.nats.io/using-nats/developer/connecting/creds

### Description [**REQUIRED**]
 A clear and concise description of the problem or missing capability...

If available users should be able to bring their own NKEYS seed or credentials file.

### Describe the solution you'd like
New options can be added for `NKeySeedFile` and `CredentialsFile` mapped to the appropriate underlying nats.go option. 

### Describe alternatives you've considered
Just using username/password.

**Comment by lenny-intel** [comment]
Note with MQTT these can come from Vault or InsecureSecrest config, based on AuthMode setting.
