### ISSUE TITLE
New messaging-based CommandClient to conveniently use the message bus communications with core command

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/go-mod-messaging#177]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for CommandClient (core-command)

### Description [**REQUIRED**]
 A clear and concise description of the problem or missing capability...
https://docs.edgexfoundry.org/2.2/design/adr/0023-North-South-Messaging/#edgex-service-internal-message-bus-requests

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by lenny-intel** [comment]
To avoid create dependency in go-mod-core-contracts on go-mod-messaging it was decide (10/04/22 Core WG) that the messaging based Command Client should be implemented in go-mode-messaging. 

The new factory function will need to be passed the map of topics described above and reference to the messaging client which is in the DIC.

**Comment by hahattan** [comment]
Just want to make sure w're trying to implement something like the original HTTP CommandClient:

```Go
type CommandClient interface {
	// AllDeviceCoreCommands returns a paginated list of MultiDeviceCoreCommandsResponse. The list contains all of the commands in the system associated with their respective device.
	// The result can be limited in a certain range by specifying the offset and limit parameters.
	// offset: The number of items to skip before starting to collect the result set. Default is 0.
	// limit: The number of items to return. Specify -1 will return all remaining items after offset. The maximum will be the MaxResultCount as defined in the configuration of service. Default is 20.
	AllDeviceCoreCommands(ctx context.Context, offset int, limit int) (responses.MultiDeviceCoreCommandsResponse, errors.EdgeX)
	// DeviceCoreCommandsByDeviceName returns all commands associated with the specified device name.
	DeviceCoreCommandsByDeviceName(ctx context.Context, deviceName string) (responses.DeviceCoreCommandResponse, errors.EdgeX)
	// IssueGetCommandByName issues the specified read command referenced by the command name to the device/sensor that is also referenced by name.
	// dsPushEvent: If set to yes, a successful GET will result in an event being pushed to the EdgeX system. Default value is no.
	// dsReturnEvent: If set to no, there will be no Event returned in the http response. Default value is yes.
	IssueGetCommandByName(ctx context.Context, deviceName string, commandName string, dsPushEvent string, dsReturnEvent string) (*responses.EventResponse, errors.EdgeX)
	// IssueGetCommandByNameWithQueryParams issues the specified read command by deviceName and commandName with additional query parameters.
	IssueGetCommandByNameWithQueryParams(ctx context.Context, deviceName string, commandName string, queryParams map[string]string) (*responses.EventResponse, errors.EdgeX)
	// IssueSetCommandByName issues the specified write command referenced by the command name to the device/sensor that is also referenced by name.
	IssueSetCommandByName(ctx context.Context, deviceName string, commandName string, settings map[string]string) (common.BaseResponse, errors.EdgeX)
	// IssueSetCommandByNameWithObject issues the specified write command and the settings supports object value type
	IssueSetCommandByNameWithObject(ctx context.Context, deviceName string, commandName string, settings map[string]interface{}) (common.BaseResponse, errors.EdgeX)
}
```

However, since we don't want to add edgex dependency in go-mod-messaging, we might need to  return `([]byte, error)`  instead. And for each service they need to decode the []byte to corresponding DTO object, is this acceptable ?

**Comment by lenny-intel** [comment]
@hahattan, good point. I didn't realize the interface definition referenced types defined in go-mod-core-contracts. 

> And for each service they need to decode the []byte to corresponding DTO object, is this acceptable ?

Nope it isn't acceptable. We need the new implementation to implement the same `CommandClient` interface so they are interchangeable in Bootstrap and App Services. 

I think having `go-mod-messaging` reference `go-mod-core-contracts` for common types is acceptable and better than having `go-mod-core-contracts`  reference `go-mod-messaging` for functionality. This also sets up moving the MessageEnvelope into `go-mod-core-contracts` DTOs in EdgeX 3.0.  

Thoughts?
