### ISSUE TITLE
Does the Messages Channel Have to Contain Pointers?

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-messaging#18]
https://github.com/edgexfoundry/go-mod-messaging/blob/04f9582c7a084d9f09edd456a75a101bff6e66ef/pkg/types/types.go#L24

Any reason other than support of legacy export-distro that this has to be pointers? Export-distro currently expects pointers to be passed through the bus, but this is needless because a message published to a bus should be immutable. Thus it's perfectly fine to pass a copy into the bus and not a mutable pointer. 

If you agree, then please remove the pointer definition so I can use it in integrating CBOR into export-distro.

**Comment by lenny-intel** [comment]
@tsconn23 , I think it is a pointer to avoid unneeded coping. If we have large CBOR messages, wouldn't we want to avoid making copies?

**Comment by tsconn23** [comment]
As discussed on the Core WG call, we'll accept the change to a non-pointer channel and then gather some stats on the overhead. If it's significant, will revisit.

**Comment by lenny-intel** [comment]
PR #19 Addressed this issue.
