### ISSUE TITLE
This may be an influential bug in the structure host_info

### ISSUE THREAD

**Issue by Pluviophile225** [edgexfoundry/go-mod-messaging#239]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
`pkg/types/host_info.go`

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

// GetHostURL returns the complete URL for the host-info configuration
func (info *HostInfo) GetHostURL() string {

	protocol := info.Protocol
	if info.Protocol == "" {
		protocol = defaultMsgProtocol
	}
	return fmt.Sprintf("%s://%s:%d", protocol, info.Host, info.Port)
}

</code></pre> 

the defaultMsgProtocol `"tcp"` does change the info.Protocol, it just be assigned to the local variable `protocol`, I guess this may cause serious bug if anyone uses this feature.

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

**Comment by lenny-intel** [comment]
@Pluviophile225 , local variable `protocol` is used in the URL string retuned. This function is not indented to modify the passed in `info` data.

**Comment by cloudxxx8** [comment]
what kinds of serious bugs or usage you are refering to?  please write down more statement or examples.

**Comment by cloudxxx8** [comment]
close this issue due to no response
