### ISSUE TITLE
Question -- Why does this repo have Dockerfiles?

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/go-mod-messaging#24]
??

It really shouldn't since these aren't published as images. The repo itself is consumed as a dependency in other applications via Go modules.

**Comment by lenny-intel** [comment]
@lranjbar , I assume these Dockerfiles are used by the verify jobs which in this case just run the unit tests, correct?

**Comment by jamesrgregg** [comment]
Guys Lisa is on sabbatical.

**Comment by jamesrgregg** [comment]
It’s because these go modules all use Jenkins pipelines which leverage the base build images for the semantic versioning.

**Comment by jamesrgregg** [comment]
The codecov.io required this for the test coverage reports as per the commit history I see from Tyler.
