### ISSUE TITLE
NATS: Jetstream tests add nats-server as a module dependency

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/go-mod-messaging#284]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 

Any service built with the `include_nats_messaging` flag.

### Is this a regression?

No.

## 🔥 Exception or Error

The JetStream package includes some tests that run against an embedded nats-server.  These are not included in the `_test` package so they end up bringing the server in as a dependency when imported.  To address we have two options.

1. Remove the tests.
2. Move the tests to appropriate _test package and export functions as needed to support move. This would also require setting up a separate go.mod for testing.  The nats client uses a similar approach that should be manageable if a little quirky.

## 🌍  Your Environment
**Deployment Environment:**

2.3 - current.  Since this is an optional dependency I don't think fixing past versions is necessary.

**Anything else relevant?**

Note the NATS go client itself has the same issue - this fix should be limited to the effect on EdgeX code.  We could revert to an earlier version of the client if needed.  https://github.com/nats-io/nats.go/issues/1311

It might be interesting to take another look at the effect of the NATS dependencies on binary size after this is fully resolved.

**Comment by wallyqs** [comment]
fwiw @AlexCuse if you were using the nats-server only for tests, it should not affect the binary size. The same for users of the nats.go client, the nats-server would not be part of the binary since only being used for tests.

**Comment by AlexCuse** [comment]
Thanks @wallyqs that is what I thought but I was second guessing myself on it since I missed this issue with tests in the main package.  It is good to know it's only effecting the build time dependencies.

The only tests we had using a server were for auto provisioning and exactly once configuration - both enough of a corner case I'm not sure it's worth setting up the double go_mod files y'all have in the client. I opened a PR to remove the tests for now once everything settles I can open another to see if we have the appetite for it here.  We could also put something into https://github.com/edgexfoundry/edgex-examples to serve as a reference.

**Comment by wallyqs** [comment]
np, we're fixing this anyway in the nats.go client since sbom tooling picks it up accidentally too.  You can see the dependencies that make it into a binary with `go version -m <binary>`, that can be helpful to confirm as well.

**Comment by lenny-intel** [comment]
> np, we're fixing this anyway in the nats.go client since sbom tooling picks it up accidentally too. You can see the dependencies that make it into a binary with `go version -m <binary>`, that can be helpful to confirm as well.

Yep, it just moved the NATs server to an indirect dependency.
