### ISSUE TITLE
support redis sentinel in current version?

### ISSUE THREAD

**Issue by fishdemon** [edgexfoundry/go-mod-messaging#303]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

support redis sentinel in current version?

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by cloudxxx8** [comment]
No, we don't use this feature in Redis.
