### ISSUE TITLE
zeromq client times out/loses connection after not sending any messages

### ISSUE THREAD

**Issue by antoniomtz** [edgexfoundry/go-mod-messaging#31]
### Issue description
When using app functions SDK to subscribe to zeromq, I notice if I stop ingesting data for a few time and then try to ingest again, the client loses connection and stops receiving events (not throwing any errors or logs). It will work again only if I restart the container.

After some investigation, this can be solved by setting TCP_KEEPALIVE, TCP_KEEPALIVE_IDLE and TCP_KEEPALIVE_INTVL through http://api.zeromq.org/3-2:zmq-setsockopt

reference: https://stackoverflow.com/a/45109409 

The golang dependency pebbe/zmq4 exposes the functions to set KEEPALIVE settings https://github.com/pebbe/zmq4/blob/master/socketset.go#L292-L315 

Another potential solution is to keep the connection alive by sending a **ping** every second or so from the publisher (core-data).

### Environment
- Ubuntu 16.04
- EdgeX Edinburgh 1.0.1
- App functions SDK v0.2.0-dev.8
- go-mod-core-contracts v0.1.0

**Comment by lenny-intel** [comment]
Note that this isn't just for app services. Export Services will have the same issue if data isn't being sent for the apparent timeout period.

**Comment by michaelestrin** [comment]
Closed due to inactivity.
