### ISSUE TITLE
how to use NATS ? 

### ISSUE THREAD

**Issue by icoco** [edgexfoundry/go-mod-messaging#327]
as topic, from the online document, this [go-mod-messaging]( https://github.com/edgexfoundry/go-mod-messaging) support NATS,

but while run code , it seem does not work , it report error : `to enable NATS message bus options please build using the flag include_nats_messaging`

it should rebuild the NATS server or how to solve this problem ?
 
thanks

**Comment by cloudxxx8** [comment]
duplicated to https://github.com/orgs/edgexfoundry/discussions/278
