### ISSUE TITLE
Tests should run cleanly when passed the -race option

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/go-mod-messaging#33]
To ensure our tests (and to some extent production code) are reliable, we should be running unit tests with the -race argument in the Makefile. Currently, the tests fail when run in this mode.

Failing tests:

TestDisconnect()

This test should succeed when passed -race, and then we should add -race to the test target in our Makefile.

**Comment by brandonforster** [comment]
Per discussion on DevOps WG call on 27 February, this has been rescoped from Geneva to Hanoi so that DevOps can address some underlying build concerns.

**Comment by jpwhitemn** [comment]
DevOps addressed
