### ISSUE TITLE
Add Redis implementation for MessageClient interface

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/go-mod-messaging#35]
Create Redis implementation of MessageClient interface. 

@andresrinivasan can provide additional detail, guidance, and support.

**Comment by lenny-intel** [comment]
@AnthonyMBonafide , please make sure your redis streams implementation handles separate connection for PublishHost and SubscribeHost (if hosts are different). This is described in this issue for MQTT implementation. THX!
https://github.com/edgexfoundry/go-mod-messaging/issues/52
