### ISSUE TITLE
Cannot connect to MQTT Message bus

### ISSUE THREAD

**Issue by jinfahua** [edgexfoundry/go-mod-messaging#49]
Below is Golang code,

```go
package main

import (
	"context"
	"fmt"
	"github.com/edgexfoundry/go-mod-core-contracts/clients/coredata"
	"github.com/edgexfoundry/go-mod-core-contracts/clients/urlclient/local"
	"github.com/edgexfoundry/go-mod-core-contracts/models"
	"github.com/edgexfoundry/go-mod-messaging/messaging"
	"github.com/edgexfoundry/go-mod-messaging/pkg/types"
	"log"
	"time"
)

func main() {
	var msgConfig2 = types.MessageBusConfig{
		PublishHost: types.HostInfo{
			Host:     "10.211.55.11",
			Port:     1883,
			Protocol: "tcp",
		},
		Optional:map[string]string{
			"ClientId": "0001_client_id",
		},
		Type:messaging.MQTT,
	}
	if msgClient, err := messaging.NewMessageClient(msgConfig2); err != nil {
		log.Fatal(err)
	} else {
		if ec := msgClient.Connect(); ec != nil {
			log.Fatal(ec)
		}
		client := coredata.NewEventClient(local.New("test1"))
		var testEvent = models.Event{Device: "demo1", Created: 123, Modified: 123, Origin: 123}
		var r1 = models.Reading{Pushed: 123, Created: 123, Origin: 123, Modified: 123, Device: "test device name", Name: "Temperature", Value: "20"}
		var r2 = models.Reading{Pushed: 123, Created: 123, Origin: 123, Modified: 123, Device: "test device name", Name: "Humidity", Value: "30"}

		testEvent.Readings = append(testEvent.Readings, r1, r2)

		data, err := client.MarshalEvent(testEvent)
		if err != nil {
			fmt.Errorf("unexpected error MarshalEvent %v", err)
		} else {
			fmt.Println(string(data))
		}

		env := types.NewMessageEnvelope([]byte(data), context.Background())
		env.ContentType = "application/json"

		if e := msgClient.Publish(env, "application"); e != nil {
			log.Fatal(e)
		} else {
			fmt.Printf("pubToAnother successful: %s\n", data)
		}
		time.Sleep(1500 * time.Millisecond)
	}
}

```

Make sure that the MQTT broker is available, but it reports timeout error.
```shell
telnet 10.211.55.11 1883
Trying 10.211.55.11...
Connected to 10.211.55.11.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
RockydeMBP-2:kuiper rockyjin$ xsql/test/test 
2020/03/31 15:02:04 Timeout occured while performing a 'Connect' operation: Unable to connect

```

**Comment by lenny-intel** [comment]
@jinfahua, I think you need to add call to client.Connect() before attempting to publish. @AnthonyMBonafide is this correct?

**Comment by AnthonyMBonafide** [comment]
> @jinfahua, I think you need to add call to client.Connect() before attempting to publish. @AnthonyMBonafide is this correct?

That is correct, you need to call connect before publishing or subscribing. However, it seems like that is being done on the first line of the outermost `else` statement.

@jinfahua , can you provide and MQTT broker logs? While developing the MQTT support I found that the reasons a connection could fail were not always provided to the client. For example, in some cases I would see the same thing you shared simply because there was no `ClientId` provided. To find that I  needed to get the logs from the MQTT server to see what the error for the closed or rejected connection is. I was using Mosquitto to test so it might be a little different. Which MQTT broker are you using? I can try to reproduce the issue.

**Comment by jinfahua** [comment]
I tested in both ``mosquitto`` & [EMQ](https://hub.docker.com/r/emqx/emqx), and it reported with the same error info. Below is the log file for mosquitto.

```
Apr  1 07:55:20 liufen mosquitto: 1585698920: New connection from 127.0.0.1 on port 1883.
Apr  1 07:55:20 liufen mosquitto: 1585698920: Client <unknown> disconnected due to protocol error.
Apr  1 07:55:20 liufen mosquitto: 1585698920: New connection from 127.0.0.1 on port 1883.
Apr  1 07:55:20 liufen mosquitto: 1585698920: Client <unknown> disconnected due to protocol error.
```

**Comment by jinfahua** [comment]
> @jinfahua, I think you need to add call to client.Connect() before attempting to publish. @AnthonyMBonafide is this correct?
Lenny, below line connects to the broker, and the error is reported by this line.
```
if ec := msgClient.Connect(); ec != nil {
			log.Fatal(ec)
		}
```

**Comment by AnthonyMBonafide** [comment]
@jinfahua , It looks like the client ID is not being propagated to the server. That is the error I would see when the underlying client attempted to connect without specifying an ID. I will try to reproduce with your example. Thank you for the response.

**Comment by AnthonyMBonafide** [comment]
I was able to run your code with a locally running Mosquitto MQTT server. The only thing I changed was the host address. I tried both `localhost` and `127.0.0.1` and was able to get the client to connect. Here are the logs from my MQTT server:

```
1585750355: mosquitto version 1.6.8 starting
1585750355: Config loaded from /mosquitto/config/mosquitto.conf.
1585750355: Opening ipv4 listen socket on port 1883.
1585750355: Opening ipv6 listen socket on port 1883.
1585750364: New connection from 172.17.0.1 on port 1883.
1585750364: New client connected from 172.17.0.1 as 0001_client_id (p2, c1, k0).
1585750365: Socket error on client 0001_client_id, disconnecting.


1585750450: New connection from 172.17.0.1 on port 1883.
1585750450: New client connected from 172.17.0.1 as 0001_client_id (p2, c1, k0).
1585750451: Socket error on client 0001_client_id, disconnecting.
```

I am using version `v0.1.16` of `go-mod-messaging` are you doing the same?

**Comment by AnthonyMBonafide** [comment]
Those errors that are present in my previous comment's logs are due to the program exiting and not properly disconnecting the client, which is expected since we are not calling `Disconnect`

**Comment by jinfahua** [comment]
@AnthonyMBonafide I used v0.1.14 previously. After switching to v0.1.16, it works. Thank you! 

What's the go-mod-messaging version number shipped with EdgeX Geneva? I think it would be better to keep same version in Kuiper as with EdgeX.

**Comment by AnthonyMBonafide** [comment]
@jinfahua , Geneva has not shipped yet. We are aiming for a code freeze later this month which will give is a better idea as to which version will be used in the release. There will most likely be at least one more patch version release to the module once the [work to add support for RedisStreams](https://github.com/edgexfoundry/go-mod-messaging/issues/35) is completed.

**Comment by jinfahua** [comment]
Thanks, the issue could be closed now.
