### ISSUE TITLE
ZeroMQ and Windows

### ISSUE THREAD

**Issue by brandonforster** [edgexfoundry/go-mod-messaging#54]
Since the ZeroMQ implementation has so many hoops to jump through and external libraries to compile, we should consider excluding ZeroMQ from all Windows based builds by default and relying on MQTT.

**Comment by cloudxxx8** [comment]
Agree, and we should put a default MQTT broker in the compose file for this

**Comment by lenny-intel** [comment]
@tsconn23, Topic for Core WG meeting this week?

**Comment by lenny-intel** [comment]
ZMQ has been deprecated and has now been removed from Windows build. Closing this issue.
