### ISSUE TITLE
Expand NewMQTTClient function to support CBOR marshaler and unmarshaler

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/go-mod-messaging#56]
Currently, the NewMQTTClient function uses JSON marshaler and unmarshaler by default. Need to have the option to specify the marshaler/unmarshaler(such as CBOR) according to the MessageBusConfig.

**Comment by jpwhitemn** [comment]
Need comes from a customer that needs MQTT trigger

**Comment by cloudxxx8** [comment]
go-mod-messaging is for edgex internal use, so we opened another issue in https://github.com/edgexfoundry/app-functions-sdk-go/issues/454 to fulfill the requirement

this currently is as design
