### ISSUE TITLE
Allow MQTT MessageHandler to receive other formats of MQTT message payload

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/go-mod-messaging#57]
The current MQTT MessageHandler only accepts the message payload that can be unmarshaled to MessageEnvelope. However, in some scenarios, the message payload may not fit the MessageEnvelope structure. e.g. when using the MQTT message client in app-service as trigger and the SubscribeHost is AWS IoT instead of EdgeX CoreData, the message payload should have its own format (in this case, it has the AWS IoT Device Shadow document format).

**Comment by cloudxxx8** [comment]
go-mod-messaging is for edgex internal use, so we opened another issue in https://github.com/edgexfoundry/app-functions-sdk-go/issues/454 to fulfill the requirement
