### ISSUE TITLE
MQTT Client Drops Subscriptions on reconnect

### ISSUE THREAD

**Issue by AlexCuse** [edgexfoundry/go-mod-messaging#80]
We have been dealing with an unstable network connection the last few days and we are seeing services subscribing through an MQTT messagebus binding left in a zombie state.  It seems like the problem is no reconnect behavior specified to the underlying paho client, so after reconnection the channels used in subscription simply go quiet.

**Comment by AlexCuse** [comment]
This ends up a little awkward because the connect handler passed to the paho client needs a reference to the outer client, but I think it will work: https://github.com/AlexCuse/go-mod-messaging/commit/493f944b29bc20614b3b850984af634f202a98bb  I need to do a little more work to get a logger in but it should be in good enough shape for me to test - I need to integrate with the branch from #75 before I can test but should be able to do it over the weekend.

**Comment by cloudxxx8** [comment]
@AlexCuse we encountered this issue before, and the resolution is to use the latest version of paho.mqtt.golang.
There are some known issue about this situation and have been fixed.

**Comment by AlexCuse** [comment]
Thanks @cloudxxx8 I will test taht out too.

**Comment by lenny-intel** [comment]
@AlexCuse, @cloudxxx8 , I have a PR to fix this issue: https://github.com/edgexfoundry/go-mod-messaging/pull/81

**Comment by AlexCuse** [comment]
Awesome tucking client creation into the Connect method is way nicer than the messed up client creation order I was messing with.
