### ISSUE TITLE
RediStreams implementation doesn't support topic wildcards

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/go-mod-messaging#99]
In our Ireland implementation, Events are now published to the Message Bus using multi level topics like: `edgex/events/<profile>/<device>/<source>`
Example:  `edgex/events/Random-Integer/Random-Integer-Device-001/Int64`

For ZMQ and MQTT clients can then subscribe using wild cards to filter what they receive.

Examples to receive all Events:
ZMQ: `edgex/events` 
MQTT: `edgex/events/#` 

Examples to receive just Events from the `Random-Integer-Device-001` device
ZMQ: `edgex/events/Random-Integer/Random-Integer-Device` 
MQTT: `edgex/events/Random-Integer/Random-Integer-Device/#` 

The `RedisStreams` implementation of the Message Bus doesn't recognize any type of wild card in the subscribe topic. 
If an Event is published to `edgex/events/Random-Integer/Random-Integer-Device-001/Int64`, the client has to subscribe to `edgex/events/Random-Integer/Random-Integer-Device-001/Int64`

**Comment by lenny-intel** [comment]
@andresrinivasan , can you please review this issue and the RedisStreams implementation in this Repo and give guidance on how we could accomplish `topic wildcards` with RedisStreams. THX!

**Comment by andresrinivasan** [comment]
Interesting. `XREAD` can read from multiple keys at the same time... Is there a dictionary or registry that tracks the [profile, device, source] tuples?

**Comment by lenny-intel** [comment]
> Is there a dictionary or registry that tracks the [profile, device, source] tuples?
No, these are simply Event metadata that are added to the publish topic to better describe the data being published so that clients can filter via subscriptions.  Ideally any/all of them could be replaced with a wild card.

With MQTT we can have the following wildcard options:

1. `edgex/events/#`, `edgex/#` or `#`
   - All events
2. `edgex/events/Random-Integer/#/Int64`
   - All events for profile `Random-Integer` that have a source of `Int64`
3. `edgex/events/Random-Integer/Random-Integer-Device-001/#`
   - All events for device `Random-Integer-Device-001` from  profile `Random-Integer`
4. `edgex/events/#/Random-Integer-Device-001/#`
   - All events for device `Random-Integer-Device-001` no matter which profile or source
5. `edgex/events/#/Random-Integer-Device-001/Int64`
   - All events for device `Random-Integer-Device-001` from source `Int64` to no matter which profile
6. `edgex/events/#/#/Int64`
   - All events for source `Int64` to no matter which profile or device

or with no wild card, which currently works with our RedisStreams MessageBus implementation 

1. `edgex/events/Random-Integer/Random-Integer-Device-001/Int64`
   - Only Events for source `Int64` on device `Random-Integer-Device-001` from profile `Random-Integer`
2. `edgex/events/Random-Integer/Random-Integer-Device-001/Int32`
   - Only Events for source `Int32` on device `Random-Integer-Device-001` from profile `Random-Integer`
